#!/bin/sh

set -e

if [ ! -d "ModSecurity" ]; then
    git clone git://github.com/SpiderLabs/ModSecurity
    pushd ModSecurity
    git co remotes/trunk
    ./autogen.sh
    ./configure --enable-standalone-module
    make
    popd
fi

if [ ! -d "owasp-modsecurity-crs" ]; then
    git clone git://github.com/SpiderLabs/owasp-modsecurity-crs etc/modsecurity_crs
fi

NGINX_VERSION=nginx-1.2.6

if [ ! -d "build" ]; then
    mkdir build
    pushd build

    curl -O http://nginx.org/download/$NGINX_VERSION.tar.gz
    tar xvzf $NGINX_VERSION.tar.gz
    popd
fi

pushd build/$NGINX_VERSION
CFLAGS="-g -O0" ./configure --with-debug --with-cc-opt='-I/usr/local/include' --with-ld-opt='-L/usr/local/lib' --prefix=`pwd`/../nginx --conf-path=conf/nginx.conf --error-log-path=logs/error.log --http-log-path=logs/access.log --with-http_geoip_module --add-module=../../ModSecurity/nginx/modsecurity

make
make install
popd

if [ ! -d "etc" ]; then
    mkdir etc
    pushd etc
    wget http://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/GeoIP.dat.gz
    wget http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz
    gunzip GeoIP.dat.gz
    gunzip GeoLiteCity.dat.gz
    popd
fi

ln -sf `pwd`/nginx.conf `pwd`/build/nginx/conf/nginx.conf
ln -sf `pwd`/modsecurity.conf `pwd`/build/nginx/conf/modsecurity.conf
ln -sf `pwd`/etc `pwd`/build/nginx/etc
